apps/common/urls.py
from django.urls import path

from apps.common import views

app_name = "common"

urlpatterns = [
    path("health-check/", views.health_check, name="health-check"),
    path("db-conn-status/", views.db_connection_status, name="db-conn-status"),
    path("project-version/", views.version, name="project-version"),
    path("test-exception/", views.TriggerExceptionView.as_view(), name="test-exception"),
    path("email-admins/", views.EmailAdminsView.as_view(), name="email-admins"),
]

apps/pages/urls.py
from django.urls import path
from django.views.generic import TemplateView

from .views import AboutPageView, IndexPageView, index_page_view2, index_page_view3

app_name = "pages"
urlpatterns = [
    path("", IndexPageView.as_view(), name="index"),
    path("about/", AboutPageView.as_view(), name="about"),
    path("fbv-index/", index_page_view2, name="fbv-index"),
    path("no-template/", index_page_view3, name="no-template"),
    path("no-app/", TemplateView.as_view(template_name="pages/index.html"), name="no-app"),
]

apps/posts/urls.py
from django.urls import path

from .views import PostDetailView

app_name = "posts"

urlpatterns = [
    path("<int:pk>", PostDetailView.as_view(), name="posts-detail"),
]

apps/users/urls.py
from django.urls import path

from apps.users.views import UserDetailView, UserRedirectView, UserUpdateView

app_name = "users"
urlpatterns = [
    path("~redirect/", UserRedirectView.as_view(), name="redirect"),
    path("~update/", UserUpdateView.as_view(), name="update"),
    path("<int:pk>/", UserDetailView.as_view(), name="detail"),
]

pages/urls.py
from django.urls import path

from .views import HomePageView
from .views import AboutPageView


app_name = "pages"
urlpatterns = [
    path("", HomePageView.as_view(), name="home"),
    path("about/", AboutPageView.as_view(), name="about"),
]

apps/templates/components/nav.html
<header>
  <div class="mb-1">
    <nav class="navbar navbar-expand-md navbar-light bg-light">
      <div class="container-fluid">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="{% url 'pages:index' %}">Hello Python</a>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'pages:index' %}">Home <span class="visually-hidden">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'pages:about' %}">About</a>
            </li>
            {% if request.user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'users:detail' request.user.pk %}">My Profile</a>
              </li>
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a class="nav-link" href="{% url 'account_logout' %}">Sign Out</a>
              </li>
            {% else %}
              {% if ACCOUNT_ALLOW_REGISTRATION %}
            <li class="nav-item">
              {# URL provided by django-allauth/account/urls.py #}
              <a id="sign-up-link" class="nav-link" href="{% url 'account_signup' %}">Sign Up</a>
            </li>
            {% endif %}
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a id="log-in-link" class="nav-link" href="{% url 'account_login' %}">Sign In</a>
              </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>

  </div>
</header>

apps/templates/components/project-urls.html
<hr/>
<h3>Django Hello, World 5 Different Ways</h3>

<ul>
  <li><a href="{% url 'pages:index' %}">/index</a> - "Traditional" approach: dedicated app for static pages and inherited TemplateView</li>
  <li><a href="{% url 'pages:about' %}">/about</a> - ... </li>
</ul>

<ul>
  <li><a href="{% url 'pages:fbv-index' %}">/fbv-index</a> - function-based view</li>
</ul>

<ul>
  <li><a href="{% url 'pages:no-template' %}">/no-template</a> - bare HttpResponse</li>
</ul>


<ul>
  <li><a href="{% url 'pages:no-app' %}">/no-app</a> - no app (bare TemplateView)</li>
</ul>

<ul>
  <li><a href="{% url 'posts:posts-detail' 1 %}">/api/posts/1</a> - models</li>
</ul>

<hr>

<h3>APIs (testing/sandbox)</h3>
<ul>
  <li><a href="{% url 'common:health-check' %}">/health-check</a> - simple API health-check</li>
  <li><a href="{% url 'common:test-exception' %}">/test-exception</a> - triggers an exception "405 Method Not Allowed", for testing</li>
  <li><a href="{% url 'common:project-version' %}">/project-version</a> - project version as defined in SEM_VER_TAG env variable</li>
  <li><a href="{% url 'common:email-admins' %}">/email-admins</a> - test celery task for sending email to admins</li>
  <li><a href="{% url 'common:db-conn-status' %}">/db-conn-status</a> - simple DB connection status check "SELECT 1"</li>

</ul>